name: Test Push

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "vgodsoe@gmail.com"
          git config --global user.name "vgodsoe"

      - name: Add Remote and Push
        env:
          PUBLIC_REPO_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
        run: |
          git remote add public https://${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/vgodsoe/sample-repo.git
          git remote -v
          git push --force public main
