# .github/workflows/sync-to-public.yml
name: Sync to Public Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1  # Ensure a fresh clone with clean state

      - name: Install Git Filter-Repo
        run: |
          pip install git-filter-repo

      - name: Debug URL
        run: echo $PUBLIC_REPO_URL
        env:
          PUBLIC_REPO_URL: ${{ secrets.PUBLIC_REPO_URL }}

      - name: Add and Check Remote
        run: |
          git remote add public $PUBLIC_REPO_URL
          git remote -v
        env:
          PUBLIC_REPO_URL: ${{ secrets.PUBLIC_REPO_URL }}

      - name: Filter and Push to Public Repo
        env:
          PUBLIC_REPO_URL: ${{ secrets.PUBLIC_REPO_URL }}
          PUBLIC_REPO_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
        run: |
          chmod +x filter_sensitive_files.sh
          ./filter_sensitive_files.sh --force

          # Set up git config to use the token
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url public https://${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/vgodsoe/sample-repo.git
          git push --force public main
