# .github/workflows/sync-to-public.yml
name: Sync to Public Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v2

      - name: Install Git Filter-Repo
        run: |
          pip install git-filter-repo
      - name: Filter and Push to Public Repo
        env:
          PUBLIC_REPO_URL: ${{ secrets.PUBLIC_REPO_URL }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          # Make the filter script executable
          chmod +x filter_sensitive_files.sh
          # Run the filter script
          ./filter_sensitive_files.sh
          # Add public remote and push changes
          git remote add public $PUBLIC_REPO_URL
          git push --force public main
