name: Copy to Public Repo (without secret files)

on:
  push:
    branches:
      - main

jobs:
  copy-to-public:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: vgodsoe/private-repo
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}
        
      - name: Change to repository directory
        run: cd $GITHUB_WORKSPACE

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git remote set-url origin https://github.com/vgodsoe/sample-repo.git
          echo "Git remote URL set"
      
      - name: Remove existing temp_repo directory
        run: rm -rf temp_repo

      - name: Create temp_repo directory
        run: mkdir temp_repo

      - name: Clone Public Repo
        run: git clone https://github.com/vgodsoe/sample-repo.git temp_repo
        
      - name: Exclude secrets
        run: rsync -av --exclude 'test_private.json' ./ temp_repo/

      - name: Remove .git from temp_repo
        run: rm -rf temp_repo/.git
        
      - name: Change dir to where content is
        run: cd temp_repo
        
      - name: Git Commit and Push
        run: |
          git add .
          git commit -m "Copy files from private to public repo"
          git push --force origin main
